### ISSUE TITLE
Missing GetRobotPose.msg

### ISSUE THREAD

**Issue by S1nM** [MarcoStb1993/robot_statemachine#1]
When I try to build a project, I get the following error. There is no file GetRobotPose.msg in the directory [msg](https://github.com/MarcoStb1993/robot_statemachine/tree/master/rsm_msgs/msg). System configuration: Ubuntu 18.04, ROS Melodic. 

`Errors     << rsm_rqt_plugins:make /home/sin/robologic_ws/logs/rsm_rqt_plugins/build.make.007.log
In file included from /home/sin/robologic_ws/build/rsm_rqt_plugins/src/moc_RSMControls.cpp:9:0:
/home/sin/robologic_ws/build/rsm_rqt_plugins/src/../../../src/robot_statemachine/rsm_rqt_plugins/src/RSMControls.h:19:10: fatal error: rsm_msgs/GetRobotPose.h: No such file or directory
 #include <rsm_msgs/GetRobotPose.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rsm_rqt_plugins.dir/src/moc_RSMControls.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/sin/robologic_ws/src/robot_statemachine/rsm_rqt_plugins/src/RSMControls.cpp:1:0:
/home/sin/robologic_ws/src/robot_statemachine/rsm_rqt_plugins/src/RSMControls.h:19:10: fatal error: rsm_msgs/GetRobotPose.h: No such file or directory
 #include <rsm_msgs/GetRobotPose.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rsm_rqt_plugins.dir/src/RSMControls.cpp.o] Error 1
make[1]: *** [CMakeFiles/rsm_rqt_plugins.dir/all] Error 2
make: *** [all] Error 2
cd /home/sin/robologic_ws/build/rsm_rqt_plugins; catkin build --get-env rsm_rqt_plugins | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << rsm_rqt_plugins:make                 [ Exited with code 2 ]      
Failed    <<< rsm_rqt_plugins                      [ 1.6 seconds ]             
Abandoned <<< rsm_additions                        [ Unrelated job failed ] `

**Comment by MarcoStb1993** [comment]
Hi Telemech,
newest [commit ](https://github.com/MarcoStb1993/robot_statemachine/commit/9b68fa4475e71ddea66086177400f4d5d47f99e6) fixes this error. I deleted it for testing and forgot to put it back in. Also, I was unaware I was working on the *master* branch all the time, now switched to kinetic-devel for development, sorry.

Regards, Marco

Note: The repository wasn't tested on Melodic so far, would be great if you could confirm if it is working (after the newest commit)!

**Comment by S1nM** [comment]
Hi MarcoStb1993, thanks for the answer. 

I ran a demo, it works for ROS Melodic. 

Regards, Max

**Comment by MarcoStb1993** [comment]
Great, thank you Max!
